---
- name: Update and Upgrade Ubuntu System
  hosts: all
  become: yes
  tasks:
    - name: Ensure the package cache is up to date
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist

    - name: Remove unused packages
      apt:
        autoremove: yes

    - name: Clean up the package cache
      apt:
        autoclean: yes
