---
- name: play1
  hosts: all
  vars:
    command:
      ping: True
      netstat: True
      ip: False
  tasks:
    - name: ping_play
      shell: ping -c5 www.google.com >> output.txt
      args:
        chdir: /tmp
      when: command.ping == 1
    - name: netstat_play
      shell: netstat -nltp >> output.txt
      args:
        chdir: /tmp
      #when: command.netstat == True
    - name: ip_play
      shell: ip a >> output.txt
      args:
        chdir: /tmp
      #when: command.ip == True
