---
- name: Fix timezones
  hosts: all
  become: true
  gather_facts: false
  vars:
    timezone_value: "Asia/Kolkata"
  tasks:
    - name: Set timezone to {{ timezone_value }}
      timezone:
        name: "{{ timezone_value }}"
